default: &default
  adapter: postgresql
  encoding: unicode
  pool: <%= ENV.fetch('RAILS_MAX_THREADS', 25) %>
  host: <%= ENV.fetch('DATABASE_HOST', '127.0.0.1') %>
  port: <%= ENV.fetch('DATABASE_PORT', 5432) %>
  database: <%= ENV['DATABASE_NAME'] %>
  username: <%= ENV['DATABASE_USERNAME'] %>
  password: <%= ENV['DATABASE_PASSWORD'] %>
development:
  <<: *default
  database: <%= ENV['DATABASE_NAME'] || 'tlstudio-development' %>
production:
  <<: *default
staging:
  <<: *default
test:
  <<: *default
  database: <%= ENV.fetch('TEST_DATABASE_NAME', 'tlstudio-test') %>
  pool: 5
